variables:
    ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates' 
    ApimPolicyRoot: '$(Build.SourcesDirectory)\Resources\ApimPolicies'

resources:
  repositories:
  - repository: self
  - repository: mon-devops
    type: github
    name: olusola-adio/mon-devops
    endpoint: 'olusola-adio'
    ref: refs/tags/v1.11.1

jobs:

- job: BuildAndTestArmTemplate
  displayName: BuildAndTestArmTemplate
  pool:
    vmImage: vs2017-win2016

  steps:
  - template: AzureDevOpsTemplates/Build/StepTemplates/mon-arm-build.yml@mon-devops
    parameters:
      ArmTemplateRoot: $(ArmTemplateRoot)
  # Getting the IP of the deployed service and writing it to a variable for posing comment
  - script: |
      message="Your build has passed"
      message="${message}.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app."
      echo "##vso[task.setvariable variable=GITHUB_COMMENT]$message"